### ISSUE TITLE
Error: command hello:world not found

### ISSUE THREAD

**Issue by jhasuraj01** [pieroproietti/oclif-pnpm#2]
when running `pnpm test` it throws an error

```
hello
    1) runs hello cmd

  hello world
    2) runs hello world cmd


  0 passing (13ms)
  2 failing

  1) hello
       runs hello cmd:
     Error: command hello not found
      at Config.runCommand (/workspaces/frontend-template/node_modules/.pnpm/@oclif+core@2.15.0_@types+node@16.18.82_typescript@4.9.5/node_modules/@oclif/core/lib/config/config.js:284:19)
      at async Object.run (/workspaces/frontend-template/node_modules/.pnpm/@oclif+test@2.5.6_@types+node@16.18.82_typescript@4.9.5/node_modules/@oclif/test/lib/command.js:21:28)
      at async Context.run (/workspaces/frontend-template/node_modules/.pnpm/fancy-test@2.0.42/node_modules/fancy-test/lib/base.js:68:25)

  2) hello world
       runs hello world cmd:
     Error: command hello:world not found
      at Config.runCommand (/workspaces/frontend-template/node_modules/.pnpm/@oclif+core@2.15.0_@types+node@16.18.82_typescript@4.9.5/node_modules/@oclif/core/lib/config/config.js:284:19)
      at async Object.run (/workspaces/frontend-template/node_modules/.pnpm/@oclif+test@2.5.6_@types+node@16.18.82_typescript@4.9.5/node_modules/@oclif/test/lib/command.js:21:28)
      at async Context.run (/workspaces/frontend-template/node_modules/.pnpm/fancy-test@2.0.42/node_modules/fancy-test/lib/base.js:68:25)
```

**Comment by pieroproietti** [comment]
Hi [jhasuraj01](https://github.com/jhasuraj01)

With penguin-eggs I use it normally and yet work - saving a lot of time compared to npm - just I lost the capabilty to update README.md with the commands and don't use normally tests.

It is a long time I published this modified version of oclif, but will be necessary to rethink it and align to actual oclif.

But, unfortunately I have not time during this period.
